### ISSUE TITLE
Arise SDK not loaded with Proton

### ISSUE THREAD

**Issue by quidamphx** [emoose/Arise-SDK#12]
Trying to use the SDK on the Steam Deck, with Proton 7.0-4 and GE 7-38 (just to rule out a problem with a specific version) As it's usually drag and drop, there shouldn't be any additional work but it won't load with the game.

I've used it in multiple PCs with success, so it's specific to usage with Proton.

Are there possibly launch arguments that need to be added in Steam or elsewhere? I've seen no mention in the documentation.

**Comment by quidamphx** [comment]
This can be fixed by adding the following to Steam launch options. It's not an issue with the SDK, just an override needed for Proton.

WINEDLLOVERRIDES=XINPUT1_3=n,b %command%

**Comment by zany130** [comment]
@quidamphx how did you get it to work setting `WINEDLLOVERRIDES=XINPUT1_3=n,b %command%` does not load it. 

however `WINEDLLOVERRIDES=XINPUT1_3=n %command%` does (can tell because of this line in the proton log `Arise-SDK 0.1.29 - https://github.com/emoose/Arise-SDK` ) but this causes the game to crash
