### ISSUE TITLE
Adding support for TAAU

### ISSUE THREAD

**Issue by aymanred121** [emoose/Arise-SDK#5]
for some reason enable TAAU by adding 
```
[/Script/Engine.RendererSettings]
r.TemporalAA.Upsampling=1
```
 in `Engine.ini` doesn't work, so it'd be nice if we could able to enable that in `Arise-SDK.ini`

**Comment by emoose** [comment]
Hmm, just checked in the code and there doesn't seem to be anything that's overwriting it, code does seem to be using the value of it for something at least.
Are you sure you have TAA enabled? IIRC there's a weird r.DefaultFeature.AntiAliasing cvar you need to set for it to actually get used, could be a chance the in-game setting isn't configuring it properly.

**Comment by aymanred121** [comment]
yes, I can confirm that TAA is working - as there are some ghosting when using lower resolutions -

**Comment by emoose** [comment]
Hmm, dug into the code around it, seems that upsampling only activates if AntiAliasingMethod == AAM_TemporalAA (2), but the game sets AntiAliasingMethod to 5, which is some custom thing that isn't part of UE4 it seems...

(UE4 would set AntiAliasingMethod based on r.DefaultFeature.AntiAliasing, but looks like they removed the code for that from here too)

If I patch it to set to 2 instead of 5 the upsampling seems to work, can actually see the difference when changing it in dev-console.

Tried patching it so upsampling would work with 5 instead of needing to put it down to 2, but that just crashed my game :/ need to check that again.

**Comment by aymanred121** [comment]
TAAU is indeed working now thx
